apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 4
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: gomescarlosdev/hello-go:v4.1
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myfamily" 
              name: goserver-volume
      
      volumes:
        - name: goserver-volume
          configMap: 
            name: configmap-app
            items:
              - key: members
                path: "family.txt"